# Custom Language File for Launcher Customizer

[ejs.app]
title = "ImaginaTechSMP - Launcher BETA"

[ejs.landing]
mediaGitHubURL = "https://www.imaginatechsmp.fr/"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.com/invite/QnSqxJkCeT"

[ejs.settings]
sourceGithubLink = "https://github.com/dscalZi/HeliosLauncher"
supportLink = "https://github.com/dscalZi/HeliosLauncher/issues"

[ejs.welcome]
welcomeHeader = "BIENVENUE SUR IMAGINATECHSMP"
welcomeDescription = "Découvrez ImaginaTechSMP : Un serveur Minecraft révolutionnaire propulsé par le mod Create. Expérimentez une aventure où l'innovation rencontre la créativité et où la construction de machines complexes est la clé du succès économique ! "
welcomeDescCTA = "Le launcher est spécialement conçu pour améliorer votre expérience de jeu. Facilité d'Installation, Mises à Jour Automatiques, Compatibilité Optimale : tout ce dont vous avez besoin en une seule solution !"
